### ISSUE TITLE
can construction elevation scale caption be placed so it reads from the right like the depth below land surface scale does? 

### ISSUE THREAD

**Issue by 1djp** [llorzol/well_construction#2]

**Comment by llorzol** [comment]
Done will commit and install on Monday

**Comment by llorzol** [comment]
Installed

**Comment by 1djp** [comment]
[like]  Polette, Danial J reacted to your message:
________________________________
From: Leonard Orzol ***@***.***>
Sent: Sunday, May 19, 2024 6:20:36 PM
To: llorzol/well_construction ***@***.***>
Cc: Polette, Danial J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [llorzol/well_construction] can construction elevation scale caption be placed so it reads from the right like the depth below land surface scale does? (Issue #2)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Installed

**Comment by 1djp** [comment]
[like]  Polette, Danial J reacted to your message:
________________________________
From: Leonard Orzol ***@***.***>
Sent: Saturday, May 18, 2024 8:47:35 PM
To: llorzol/well_construction ***@***.***>
Cc: Polette, Danial J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [llorzol/well_construction] can construction elevation scale caption be placed so it reads from the right like the depth below land surface scale does? (Issue #2)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #2<https://github.com/llorzol/well_construction/issues/2> as completed.

**Comment by 1djp** [comment]
Flipping crowds nearby elevation values. Can a standoff be applied to resolve that? Otherwise, lookin' good.
