### ISSUE TITLE
can construction elevation scale be in NGVD88?

### ISSUE THREAD

**Issue by 1djp** [llorzol/well_construction#3]

**Comment by llorzol** [comment]
Using the datum that has been assigned in the sitefile information
alt_datum_cd "NGVD29"
Needs to be changed in NWIS

**Comment by llorzol** [comment]
Using the datum that has been assigned in the sitefile information
alt_datum_cd "NGVD29"
Needs to be changed in NWIS

**Comment by 1djp** [comment]
See comment in Teams. May or may not be readily resolvable.
