### ISSUE TITLE
construction explanation fill missing

### ISSUE THREAD

**Issue by 1djp** [llorzol/well_construction#4]

**Comment by llorzol** [comment]
Done will commit and install on Monday

**Comment by llorzol** [comment]
Installed
test site
https://staging-or.water/well_construction/index.html?site_no=433152121281301

**Comment by 1djp** [comment]
[like]  Polette, Danial J reacted to your message:
________________________________
From: Leonard Orzol ***@***.***>
Sent: Sunday, May 19, 2024 6:19:53 PM
To: llorzol/well_construction ***@***.***>
Cc: Polette, Danial J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [llorzol/well_construction] construction explanation fill missing (Issue #4)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Installed
test site
https://staging-or.water/well_construction/index.html?site_no=433152121281301

**Comment by 1djp** [comment]
Lookin' good.
